##############################
### WBC Weight Gain Parameters
##############################
W_Centroidal: 100
W_swingLeg: 10
W_JointAcc: 1
W_CenAngMom_Compen: 1
W_qddot_regul: 0.001
W_rf_regul: 0.001
W_tau_regul: 0.001

JointAccLimit:
  qddot: 120

##############################
### Tracking Tasks PD Gain Parameters
##############################
CentroidalTask:
  com_kp: [100, 100, 100]
  com_kd: [5, 5, 5]
  orientation_kp: [1000, 1000, 1000]
  orientation_kd: [10, 10, 10]

SwingTask:
  kp: [1000, 1000, 1000]
  kd: [40, 40, 40]

JointAccTask:
  joints: [0, 1, 2, 3, 4, 5, 6, 7, 8]
  kp: [700, 700, 700, 700, 700, 700, 700, 700, 700]
  kd: [40, 40, 40, 40, 40, 40, 40, 40, 40]

##############################
### Constraint Parameters
##############################
ContactWrench:
  k_f: 1.0
  k_mu: 0.8
