##############################
### WBC Weight Gain Parameters
##############################
W_Centroidal: 25
W_swingLeg: 50
W_JointAcc: 60
W_CenAngMom_Compen: 1
W_CentroidalForce: 200
W_RollAngularMomentum: 500
W_SwingLegRollMomentum: 7000
W_ArmRollMomentum: 500
W_SwingLateralAccel: 1000
W_TorsoYawJointAcc: 7000
W_wheelAccel: 100
W_qddot_regul: 0.0001
W_rf_regul: 0.0001
W_tau_regul: 0.0001

JointAccLimit:
  qddot: 120

##############################
### Tracking Tasks PD Gain Parameters
##############################
CentroidalTask:
  com_kp: [160, 160, 500]
  com_kd: [10, 10, 15]
  orientation_kp: [50, 200, 10]
  orientation_kd: [10, 20, 1]

SwingTask:
  kp: [1000, 300, 1000]
  kd: [40, 2, 40]

JointAccTask:
  joints: [0, 1, 2, 3, 4, 5, 6, 7, 8]
  kp: [300, 300, 300, 300, 300, 300, 300, 300, 300]
  kd: [30, 30, 30, 30, 30, 30, 30, 30, 30]

TorsoYawJointAccTask:
  joint: 0
  q_d_deg: 0.0
  kp: 100
  kd: 10

##############################
### Constraint Parameters
##############################
ContactWrench:
  k_f: 0.7
  k_mu: 0.3
